OPENAI_API_KEY = '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'

NOTION_INTEGRATION_TOKEN = 'secret_UCtPaCu0JLlQrpyB1aJ5BCvOawxOaTUPFSAY07UfMyE'
NOTION_DATABASE_ID = ''
NOTION_DATABASE_ID_NONDOMAIN = ''